apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: ftloc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ftloc
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: ftloc
        tier: backend
        track: stable
    spec:
      containers:
      - name: backend-ftloc
        imagePullPolicy: Never
        image: ftloc-backend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8001
